package com.murallaromana.dam.segundo.ogandobritoosirisjuniorproyectopmdm

class PeliculasDaoMockImpl  {

    fun getTodos() = listOf(
        Pelicula("Los otros(2001)","Terror", "Alejando Amenabar", "2001","https://www.themoviedb.org/t/p/w600_and_h900_bestv2/w6L1ciqLE0V9Q4l2N24lchXIYR.jpg","Isla de Jersey, 1945. La Segunda Guerra Mundial ha terminado, pero el marido de Grace (Nicole Kidman) no vuelve. Sola en un aislado caserón victoriano de la isla de Jersey, educa a sus hijos dentro de rígidas normas religiosas. Los niños sufren una extraña enfermedad: no pueden recibir directamente la luz del día. Los tres nuevos sirvientes que se incorporan a la vida familiar deben aprender una regla vital: la casa estará siempre en penumbra, y nunca se abrirá una puerta si no se ha cerrado la anterior. Pero el estricto orden que Grace ha impuesto se verá desafiado por circunstancias que escapan a su control.","https://larepublica.pe/resizer/iNu4A0SslHhsUsf59z6lmWNNApQ=/1250x735/top/smart/cloudfront-us-east-1.images.arcpublishing.com/gruporepublica/ZVYXXFJ7RFGKLMKPYWS5S43QSQ.jpg"),
        Pelicula("Eternals(2021)","Fantasy", " Chloé Zhao", "2021","https://www.themoviedb.org/t/p/w600_and_h900_bestv2/zpSW0AswPGYZQvLVsHbAcTzEyy3.jpg","Hace millones de años, los seres cósmicos conocidos como los Celestiales comenzaron a experimentar genéticamente con los humanos. Su intención era crear individuos superpoderosos que hicieran únicamente el bien, pero algo salió mal y aparecieron los Desviantes, destruyendo y creando el caos a su paso. Ambas razas se han enfrentado en una eterna lucha de poder a lo largo de la historia. En medio de esta guerra, Ikaris y Sersi tratarán de vivir su propia historia de amor.","https://i.blogs.es/aecec8/eternals-logo/1366_2000.jpeg"),
        Pelicula("El padrino(1977)","Crimen", "Francis ford Coppola", "1977","https://www.themoviedb.org/t/p/w600_and_h900_bestv2/sqtq7uH7xwU9Ia2rWEVO7AQXKYO.jpg","América, años 40. Don Vito Corleone (Marlon Brando) es el respetado y temido jefe de una de las cinco familias de la mafia de Nueva York. Tiene cuatro hijos: Connie (Talia Shire), el impulsivo Sonny (James Caan), el pusilánime Fredo (John Cazale) y Michael (Al Pacino), que no quiere saber nada de los negocios de su padre. Cuando Corleone, en contra de los consejos de 'Il consigliere' Tom Hagen (Robert Duvall), se niega a participar en el negocio de las drogas, el jefe de otra banda ordena su asesinato. Empieza entonces una violenta y cruenta guerra entre las familias mafiosas.","https://culturayciencia.diariocronicas.com/wp-content/uploads/2020/08/El-Padrino-1.jpg"),
        Pelicula("Los Intocables(1987)","Policiaco", "Brian la palma", "1987","https://www.themoviedb.org/t/p/w600_and_h900_bestv2/815jGGCOfEGTBKH4yQ18Eie3J5m.jpg","Chicago, años 30. Impera la 'Ley seca', que prohíbe la venta de alcohol. El idealista agente federal Eliot Ness (Kevin Costner) persigue implacablemente al gángster Al Capone (Robert De Niro), amo absoluto del crimen organizado en la ciudad. La falta de pruebas le impide acusarlo de asesinato, extorsión y comercio ilegal de alcohol, pero Ness, con la ayuda de un par de intachables policías (Andy Garcia y Charles Martin Smith) reclutados con la ayuda de un astuto agente (Sean Connery), intentará encontrar algún medio para inculparlo por otra clase de delitos.","https://i2.wp.com/www.8sorbosdeinspiracion.com/wp-content/uploads/2017/12/8sorbos-cine-Los-intocables-de-Elliot-Ness.jpg?w=897"),
    )



}